### PR TITLE
Scripts for fetching, cleaning and assembling webdatasets

### PR DESCRIPTION
**Pull request by alcunha**
Added the basic code for fetching images, cleaning the dataset and creating webdatasets.

I still need to create a readme file to better explain the entire pipeline.

### CODE REVIEW

**Comment by leonardpasi** [comment]
Thank you so much @alcunha for this PR! I haven't reviewed it in depth yet, but the code looks very clean. Waiting for the readme

**Comment by mihow** [comment]
This is looking really great! I was able to install the dependencies with poetry and call the scripts and run the `fetch_images.py` script using a DWCA zip file from a GBIF query and it worked! I'll wait for the README for your other stages after you get back.

One note: It's more standard for CLI parameters to use hyphens instead of underscores. e.g. `--dataset-path` instead of `--dataset_path`

**Comment by alcunha** [comment]
> This is looking really great! I was able to install the dependencies with poetry and call the scripts and run the `fetch_images.py` script using a DWCA zip file from a GBIF query and it worked! I'll wait for the README for your other stages after you get back.
> 
> One note: It's more standard for CLI parameters to use hyphens instead of underscores. e.g. `--dataset-path` instead of `--dataset_path`

Done

**Comment by mihow** [comment]
@alcunha if you add a basic README with the minimum parameters to run each of these scripts that will be enough to start!

**Comment by alcunha** [comment]
I have included a diagram in the README file to describe the pipeline. I added the picture to a new "assets" folder because the diagram should be updated if the process changes, and it should be tracked by Git.

**Comment by alcunha** [comment]
I've added a basic description of the flags needed to run the scripts for the webdataset creation pipeline. I think the PR is ready for review.

**Comment by alcunha** [comment]
Added life-stage prediction optional step to the pipeline. See #9

**Review by mihow — APPROVED** [review]
Fantastic work, thank you @alcunha.

**Pull request merged**
